name: daily-bundler

on:
  schedule:
    - cron: '0 0 * * *'

jobs:
  daily_bundler:
    runs-on: ubuntu-16.04
    strategy:
      matrix:
        ruby: [ ruby-head ]
    env:
      RGV: ..
    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler: none
      - name: Prepare dependencies
        run: |
          sudo apt-get install graphviz -y
          bin/rake spec:parallel_deps
        working-directory: ./bundler
      - name: Run Test
        run: |
          bin/rake spec:all
        working-directory: ./bundler
    timeout-minutes: 60
